routes:
  /blog/tags: blog/taxonomies
  /search: search
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
  /national-parks/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
collections:
  blog: '/blog/{slug}'
  national-parks: '/national-parks/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
